#+feature dynamic-literals
package ult_cpu

AddrModeSet :: bit_set[AddrMode]

AddrModeSetNone: AddrModeSet : {}

AddrModeSetAll: AddrModeSet : {
    .Imm,
    .ImmPtr,
    .Reg,
    .RegPtr,
    .ImmPlusReg,
    .ImmPlusRegPtr,
    .RegPlusReg,
    .RegPlusRegPtr,
    .ImmMinusReg,
    .ImmMinusRegPtr,
    .RegMinusReg,
    .RegMinusRegPtr,
    .ImmTimesReg,
    .ImmTimesRegPtr,
    .RegTimesReg,
    .RegTimesRegPtr,
}

AddrModeSetWriteable: AddrModeSet : {
    .ImmPtr,
    .Reg,
    .RegPtr,
    .ImmPlusRegPtr,
    .RegPlusRegPtr,
    .ImmMinusRegPtr,
    .RegMinusRegPtr,
    .ImmTimesRegPtr,
    .RegTimesRegPtr,
}

InstTableArgs :: struct {
    Arg1: AddrModeSet,
    Arg2: AddrModeSet,
    Arg3: AddrModeSet,
    Arg4: AddrModeSet,
}

Bits :: enum u8 {
    B0,
    B8,
    B16,
    B32,
}

InstTableEntry :: struct {
    OpCode:    OpCode,
    ArgCount:  u8,
    Args:      InstTableArgs,
    ArgBits:   [4]Bits,
    Proc:      InstProc,
    BaseTicks: u64,
    HandlesPC: bool,
    Mnemonic:  string,
}

InstTable: map[OpCode]InstTableEntry = {
    .Mov     = {.Mov, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_mov, 0, false, "mov"},
    .Lod     = {.Lod, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_lod, 0, false, "lod"},
    .Sto     = {.Sto, 2, {AddrModeSetAll, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_sto, 0, false, "sto"},
    .Inc     = {.Inc, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B32, .B0, .B0, .B0}, inst_inc, 0, false, "inc"},
    .Icc     = {.Icc, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B32, .B0, .B0, .B0}, inst_icc, 0, false, "icc"},
    .Dec     = {.Dec, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B32, .B0, .B0, .B0}, inst_dec, 0, false, "dec"},
    .Dcb     = {.Dcb, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B32, .B0, .B0, .B0}, inst_dcb, 0, false, "dcb"},
    .Add     = {.Add, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_add, 0, false, "add"},
    .Adc     = {.Adc, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_adc, 0, false, "adc"},
    .Sub     = {.Sub, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_sub, 0, false, "sub"},
    .Sbb     = {.Sbb, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_sbb, 0, false, "sbb"},
    .Mul     = {.Mul, 3, {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone}, {.B32, .B32, .B32, .B0}, inst_mul, 0, false, "mul"},
    .Mls     = {.Mls, 3, {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone}, {.B32, .B32, .B32, .B0}, inst_mls, 0, false, "mls"},
    .Div     = {.Div, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_div, 0, false, "div"},
    .Dvs     = {.Dvs, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_dvs, 0, false, "dvs"},
    .Mod     = {.Mod, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_mod, 0, false, "mod"},
    .Mds     = {.Mds, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_mds, 0, false, "mds"},
    .Dvm     = {.Dvm, 3, {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone}, {.B32, .B32, .B32, .B0}, inst_dvm, 0, false, "dvm"},
    .Dms     = {.Dms, 3, {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone}, {.B32, .B32, .B32, .B0}, inst_dms, 0, false, "dms"},
    .Rem     = {.Rem, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_rem, 0, false, "rem"},
    .Rms     = {.Rms, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_rms, 0, false, "rms"},
    .Dvr     = {.Dvr, 3, {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone}, {.B32, .B32, .B32, .B0}, inst_dvr, 0, false, "dvr"},
    .Drs     = {.Drs, 3, {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone}, {.B32, .B32, .B32, .B0}, inst_drs, 0, false, "drs"},
    .Cpl     = {.Cpl, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B32, .B0, .B0, .B0}, inst_cpl, 0, false, "cpl"},
    .And     = {.And, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_and, 0, false, "and"},
    .Ior     = {.Ior, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_ior, 0, false, "ior"},
    .Xor     = {.Xor, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_xor, 0, false, "xor"},
    .Bst     = {.Bst, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_bst, 0, false, "bst"},
    .Brs     = {.Brs, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_brs, 0, false, "brs"},
    .Bts     = {.Bts, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_bts, 0, false, "bts"},
    .Shl     = {.Shl, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_shl, 0, false, "shl"},
    .Asr     = {.Asr, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_asr, 0, false, "asr"},
    .Lsr     = {.Lsr, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_lsr, 0, false, "lsr"},
    .Rtl     = {.Rtl, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_rtl, 0, false, "rtl"},
    .Rtr     = {.Rtr, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_rtr, 0, false, "rtr"},
    .Rlc     = {.Rlc, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_rlc, 0, false, "rlc"},
    .Rrc     = {.Rrc, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_rrc, 0, false, "rrc"},
    .Cmp     = {.Cmp, 2, {AddrModeSetAll, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_cmp, 0, false, "cmp"},
    .Jmp     = {.Jmp, 1, {AddrModeSetAll, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B32, .B0, .B0, .B0}, inst_jmp, 0, true, "jmp"},
    .Cjp     = {.Cjp, 2, {AddrModeSet{.Imm}, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B32, .B0, .B0}, inst_cjp, 0, true, "cjp"},
    .Cal     = {.Cal, 1, {AddrModeSetAll, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B32, .B0, .B0, .B0}, inst_cal, 0, true, "cal"},
    .Ccl     = {.Ccl, 2, {AddrModeSet{.Imm}, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B32, .B0, .B0}, inst_ccl, 0, true, "ccl"},
    .Ret     = {.Ret, 0, {AddrModeSetNone, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B0, .B0, .B0, .B0}, inst_ret, 0, true, "ret"},
    .Irt     = {.Irt, 0, {AddrModeSetNone, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B0, .B0, .B0, .B0}, inst_irt, 0, true, "irt"},
    .Crt     = {.Crt, 1, {AddrModeSet{.Imm}, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B8, .B0, .B0, .B0}, inst_crt, 0, true, "crt"},
    .Cir     = {.Cir, 1, {AddrModeSet{.Imm}, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B8, .B0, .B0, .B0}, inst_cir, 0, true, "cir"},
    .Ien     = {.Ien, 0, {AddrModeSetNone, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B0, .B0, .B0, .B0}, inst_ien, 0, false, "ien"},
    .Idi     = {.Idi, 0, {AddrModeSetNone, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B0, .B0, .B0, .B0}, inst_idi, 0, false, "idi"},
    .Iti     = {.Iti, 1, {AddrModeSetAll, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B32, .B0, .B0, .B0}, inst_iti, 0, false, "iti"},
    .Imi     = {.Imi, 1, {AddrModeSetAll, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B32, .B0, .B0, .B0}, inst_imi, 0, false, "imi"},
    .Int     = {.Int, 1, {AddrModeSetAll, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B16, .B0, .B0, .B0}, inst_int, 0, true, "int"},
    .Psh     = {.Psh, 1, {AddrModeSetAll, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B32, .B0, .B0, .B0}, inst_psh, 0, false, "psh"},
    .Psr     = {.Psr, 1, {AddrModeSetAll, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B32, .B0, .B0, .B0}, inst_psr, 0, false, "psr"},
    .Pzm     = {.Pzm, 1, {AddrModeSetAll, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B32, .B0, .B0, .B0}, inst_pzm, 0, false, "pzm"},
    .Pop     = {.Pop, 0, {AddrModeSetNone, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B0, .B0, .B0, .B0}, inst_pop, 0, false, "pop"},
    .Ppb     = {.Ppb, 1, {AddrModeSetAll, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B32, .B0, .B0, .B0}, inst_ppb, 0, false, "ppb"},
    .Pek     = {.Pek, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B32, .B0, .B0, .B0}, inst_pek, 0, false, "pek"},
    .Pko     = {.Pko, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_pko, 0, false, "pko"},
    .Ppr     = {.Ppr, 1, {AddrModeSetAll, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B32, .B0, .B0, .B0}, inst_ppr, 0, false, "ppr"},
    .Out     = {.Out, 2, {AddrModeSetAll, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B8, .B0, .B0}, inst_out, 0, false, "out"},
    .Inp     = {.Inp, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B16, .B0, .B0}, inst_inp, 0, false, "inp"},
    .Hlt     = {.Hlt, 0, {AddrModeSetNone, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B0, .B0, .B0, .B0}, inst_hlt, 0, false, "hlt"},
    .Brk     = {.Brk, 0, {AddrModeSetNone, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B0, .B0, .B0, .B0}, inst_brk, 0, false, "brk"},
    .Nop     = {.Nop, 0, {AddrModeSetNone, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B0, .B0, .B0, .B0}, inst_nop, 0, false, "nop"},
    .Mov8    = {.Mov8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_mov8, 0, false, "mov8"},
    .Lod8    = {.Lod8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B32, .B0, .B0}, inst_lod8, 0, false, "lod8"},
    .Sto8    = {.Sto8, 2, {AddrModeSetAll, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B8, .B0, .B0}, inst_sto8, 0, false, "sto8"},
    .Inc8    = {.Inc8, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B8, .B0, .B0, .B0}, inst_inc8, 0, false, "inc8"},
    .Icc8    = {.Icc8, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B8, .B0, .B0, .B0}, inst_icc8, 0, false, "icc8"},
    .Dec8    = {.Dec8, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B8, .B0, .B0, .B0}, inst_dec8, 0, false, "dec8"},
    .Dcb8    = {.Dcb8, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B8, .B0, .B0, .B0}, inst_dcb8, 0, false, "dcb8"},
    .Add8    = {.Add8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_add8, 0, false, "add8"},
    .Adc8    = {.Adc8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_adc8, 0, false, "adc8"},
    .Sub8    = {.Sub8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_sub8, 0, false, "sub8"},
    .Sbb8    = {.Sbb8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_sbb8, 0, false, "sbb8"},
    .Mul8    = {.Mul8, 3, {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone}, {.B8, .B8, .B8, .B0}, inst_mul8, 0, false, "mul8"},
    .Mls8    = {.Mls8, 3, {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone}, {.B8, .B8, .B8, .B0}, inst_mls8, 0, false, "mls8"},
    .Div8    = {.Div8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_div8, 0, false, "div8"},
    .Dvs8    = {.Dvs8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_dvs8, 0, false, "dvs8"},
    .Mod8    = {.Mod8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_mod8, 0, false, "mod8"},
    .Mds8    = {.Mds8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_mds8, 0, false, "mds8"},
    .Dvm8    = {.Dvm8, 3, {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone}, {.B8, .B8, .B8, .B0}, inst_dvm8, 0, false, "dvm8"},
    .Dms8    = {.Dms8, 3, {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone}, {.B8, .B8, .B8, .B0}, inst_dms8, 0, false, "dms8"},
    .Rem8    = {.Rem8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_rem8, 0, false, "rem8"},
    .Rms8    = {.Rms8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_rms8, 0, false, "rms8"},
    .Dvr8    = {.Dvr8, 3, {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone}, {.B8, .B8, .B8, .B0}, inst_dvr8, 0, false, "dvr8"},
    .Drs8    = {.Drs8, 3, {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone}, {.B8, .B8, .B8, .B0}, inst_drs8, 0, false, "drs8"},
    .Cpl8    = {.Cpl8, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B8, .B0, .B0, .B0}, inst_cpl8, 0, false, "cpl8"},
    .And8    = {.And8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_and8, 0, false, "and8"},
    .Ior8    = {.Ior8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_ior8, 0, false, "ior8"},
    .Xor8    = {.Xor8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_xor8, 0, false, "xor8"},
    .Bst8    = {.Bst8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_bst8, 0, false, "bst8"},
    .Brs8    = {.Brs8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_brs8, 0, false, "brs8"},
    .Bts8    = {.Bts8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_bts8, 0, false, "bts8"},
    .Shl8    = {.Shl8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_shl8, 0, false, "shl8"},
    .Asr8    = {.Asr8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_asr8, 0, false, "asr8"},
    .Rtl8    = {.Rtl8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_rtl8, 0, false, "rtl8"},
    .Rtr8    = {.Rtr8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_rtr8, 0, false, "rtr8"},
    .Rlc8    = {.Rlc8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_rlc8, 0, false, "rlc8"},
    .Rrc8    = {.Rrc8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_rrc8, 0, false, "rrc8"},
    .Cmp8    = {.Cmp8, 2, {AddrModeSetAll, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_cmp8, 0, false, "cmp8"},
    .Psh8    = {.Psh8, 1, {AddrModeSetAll, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B8, .B0, .B0, .B0}, inst_psh8, 0, false, "psh8"},
    .Pop8    = {.Pop8, 0, {AddrModeSetNone, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B0, .B0, .B0, .B0}, inst_pop8, 0, false, "pop8"},
    .Pek8    = {.Pek8, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B8, .B0, .B0, .B0}, inst_pek8, 0, false, "pek8"},
    .Pko8    = {.Pko8, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B8, .B8, .B0, .B0}, inst_pko8, 0, false, "pko8"},
    .Mov16   = {.Mov16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_mov16, 0, false, "mov16"},
    .Lod16   = {.Lod16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B32, .B0, .B0}, inst_lod16, 0, false, "lod16"},
    .Sto16   = {.Sto16, 2, {AddrModeSetAll, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B16, .B0, .B0}, inst_sto16, 0, false, "sto16"},
    .Inc16   = {.Inc16, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B16, .B0, .B0, .B0}, inst_inc16, 0, false, "inc16"},
    .Icc16   = {.Icc16, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B16, .B0, .B0, .B0}, inst_icc16, 0, false, "icc16"},
    .Dec16   = {.Dec16, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B16, .B0, .B0, .B0}, inst_dec16, 0, false, "dec16"},
    .Dcb16   = {.Dcb16, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B16, .B0, .B0, .B0}, inst_dcb16, 0, false, "dcb16"},
    .Add16   = {.Add16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_add16, 0, false, "add16"},
    .Adc16   = {.Adc16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_adc16, 0, false, "adc16"},
    .Sub16   = {.Sub16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_sub16, 0, false, "sub16"},
    .Sbb16   = {.Sbb16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_sbb16, 0, false, "sbb16"},
    .Mul16   = {.Mul16, 3, {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone}, {.B16, .B16, .B16, .B0}, inst_mul16, 0, false, "mul16"},
    .Mls16   = {.Mls16, 3, {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone}, {.B16, .B16, .B16, .B0}, inst_mls16, 0, false, "mls16"},
    .Div16   = {.Div16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_div16, 0, false, "div16"},
    .Dvs16   = {.Dvs16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_dvs16, 0, false, "dvs16"},
    .Mod16   = {.Mod16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_mod16, 0, false, "mod16"},
    .Mds16   = {.Mds16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_mds16, 0, false, "mds16"},
    .Dvm16   = {.Dvm16, 3, {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone}, {.B16, .B16, .B16, .B0}, inst_dvm16, 0, false, "dvm16"},
    .Dms16   = {.Dms16, 3, {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone}, {.B16, .B16, .B16, .B0}, inst_dms16, 0, false, "dms16"},
    .Rem16   = {.Rem16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_rem16, 0, false, "rem16"},
    .Rms16   = {.Rms16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_rms16, 0, false, "rms16"},
    .Dvr16   = {.Dvr16, 3, {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone}, {.B16, .B16, .B16, .B0}, inst_dvr16, 0, false, "dvr16"},
    .Drs16   = {.Drs16, 3, {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone}, {.B16, .B16, .B16, .B0}, inst_drs16, 0, false, "drs16"},
    .Cpl16   = {.Cpl16, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B16, .B0, .B0, .B0}, inst_cpl16, 0, false, "cpl16"},
    .And16   = {.And16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_and16, 0, false, "and16"},
    .Ior16   = {.Ior16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_ior16, 0, false, "ior16"},
    .Xor16   = {.Xor16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_xor16, 0, false, "xor16"},
    .Bst16   = {.Bst16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_bst16, 0, false, "bst16"},
    .Brs16   = {.Brs16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_brs16, 0, false, "brs16"},
    .Bts16   = {.Bts16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_bts16, 0, false, "bts16"},
    .Shl16   = {.Shl16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_shl16, 0, false, "shl16"},
    .Asr16   = {.Asr16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_asr16, 0, false, "asr16"},
    .Rtl16   = {.Rtl16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_rtl16, 0, false, "rtl16"},
    .Rtr16   = {.Rtr16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_rtr16, 0, false, "rtr16"},
    .Rlc16   = {.Rlc16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_rlc16, 0, false, "rlc16"},
    .Rrc16   = {.Rrc16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_rrc16, 0, false, "rrc16"},
    .Cmp16   = {.Cmp16, 2, {AddrModeSetAll, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_cmp16, 0, false, "cmp16"},
    .Psh16   = {.Psh16, 1, {AddrModeSetAll, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B16, .B0, .B0, .B0}, inst_psh16, 0, false, "psh16"},
    .Pop16   = {.Pop16, 0, {AddrModeSetNone, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B0, .B0, .B0, .B0}, inst_pop16, 0, false, "pop16"},
    .Pek16   = {.Pek16, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B16, .B0, .B0, .B0}, inst_pek16, 0, false, "pek16"},
    .Pko16   = {.Pko16, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B16, .B16, .B0, .B0}, inst_pko16, 0, false, "pko16"},
    .Inc16x2 = {
        .Inc16x2,
        1,
        {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone},
        {.B32, .B0, .B0, .B0},
        inst_inc16x2,
        0,
        false,
        "inc16x2",
    },
    .Dec16x2 = {
        .Dec16x2,
        1,
        {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone},
        {.B32, .B0, .B0, .B0},
        inst_dec16x2,
        0,
        false,
        "dec16x2",
    },
    .Add16x2 = {
        .Add16x2,
        2,
        {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone},
        {.B32, .B32, .B0, .B0},
        inst_add16x2,
        0,
        false,
        "add16x2",
    },
    .Sub16x2 = {
        .Sub16x2,
        2,
        {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone},
        {.B32, .B32, .B0, .B0},
        inst_sub16x2,
        0,
        false,
        "sub16x2",
    },
    .Mul16x2 = {
        .Mul16x2,
        2,
        {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone},
        {.B32, .B32, .B0, .B0},
        inst_mul16x2,
        0,
        false,
        "mul16x2",
    },
    .Mls16x2 = {
        .Mls16x2,
        2,
        {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone},
        {.B32, .B32, .B0, .B0},
        inst_mls16x2,
        0,
        false,
        "mls16x2",
    },
    .Div16x2 = {
        .Div16x2,
        2,
        {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone},
        {.B32, .B32, .B0, .B0},
        inst_div16x2,
        0,
        false,
        "div16x2",
    },
    .Dvs16x2 = {
        .Dvs16x2,
        2,
        {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone},
        {.B32, .B32, .B0, .B0},
        inst_dvs16x2,
        0,
        false,
        "dvs16x2",
    },
    .Mod16x2 = {
        .Mod16x2,
        2,
        {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone},
        {.B32, .B32, .B0, .B0},
        inst_mod16x2,
        0,
        false,
        "mod16x2",
    },
    .Mds16x2 = {
        .Mds16x2,
        2,
        {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone},
        {.B32, .B32, .B0, .B0},
        inst_mds16x2,
        0,
        false,
        "mds16x2",
    },
    .Dvm16x2 = {
        .Dvm16x2,
        3,
        {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone},
        {.B32, .B32, .B32, .B0},
        inst_dvm16x2,
        0,
        false,
        "dvm16x2",
    },
    .Dms16x2 = {
        .Dms16x2,
        3,
        {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone},
        {.B32, .B32, .B32, .B0},
        inst_dms16x2,
        0,
        false,
        "dms16x2",
    },
    .Rem16x2 = {
        .Rem16x2,
        2,
        {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone},
        {.B32, .B32, .B0, .B0},
        inst_rem16x2,
        0,
        false,
        "rem16x2",
    },
    .Rms16x2 = {
        .Rms16x2,
        2,
        {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone},
        {.B32, .B32, .B0, .B0},
        inst_rms16x2,
        0,
        false,
        "rms16x2",
    },
    .Dvr16x2 = {
        .Dvr16x2,
        3,
        {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone},
        {.B32, .B32, .B32, .B0},
        inst_dvr16x2,
        0,
        false,
        "dvr16x2",
    },
    .Drs16x2 = {
        .Drs16x2,
        3,
        {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone},
        {.B32, .B32, .B32, .B0},
        inst_drs16x2,
        0,
        false,
        "drs16x2",
    },
    .Bst16x2 = {
        .Bst16x2,
        2,
        {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone},
        {.B32, .B32, .B0, .B0},
        inst_bst16x2,
        0,
        false,
        "bst16x2",
    },
    .Brs16x2 = {
        .Brs16x2,
        2,
        {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone},
        {.B32, .B32, .B0, .B0},
        inst_brs16x2,
        0,
        false,
        "brs16x2",
    },
    .Shl16x2 = {
        .Shl16x2,
        2,
        {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone},
        {.B32, .B32, .B0, .B0},
        inst_shl16x2,
        0,
        false,
        "shl16x2",
    },
    .Asr16x2 = {
        .Asr16x2,
        2,
        {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone},
        {.B32, .B32, .B0, .B0},
        inst_asr16x2,
        0,
        false,
        "asr16x2",
    },
    .Rtl16x2 = {
        .Rtl16x2,
        2,
        {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone},
        {.B32, .B32, .B0, .B0},
        inst_rtl16x2,
        0,
        false,
        "rtl16x2",
    },
    .Rtr16x2 = {
        .Rtr16x2,
        2,
        {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone},
        {.B32, .B32, .B0, .B0},
        inst_rtr16x2,
        0,
        false,
        "rtr16x2",
    },
    .Inc8x4  = {.Inc8x4, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B32, .B0, .B0, .B0}, inst_inc8x4, 0, false, "inc8x4"},
    .Dec8x4  = {.Dec8x4, 1, {AddrModeSetWriteable, AddrModeSetNone, AddrModeSetNone, AddrModeSetNone}, {.B32, .B0, .B0, .B0}, inst_dec8x4, 0, false, "dec8x4"},
    .Add8x4  = {.Add8x4, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_add8x4, 0, false, "add8x4"},
    .Sub8x4  = {.Sub8x4, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_sub8x4, 0, false, "sub8x4"},
    .Mul8x4  = {.Mul8x4, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_mul8x4, 0, false, "mul8x4"},
    .Mls8x4  = {.Mls8x4, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_mls8x4, 0, false, "mls8x4"},
    .Div8x4  = {.Div8x4, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_div8x4, 0, false, "div8x4"},
    .Dvs8x4  = {.Dvs8x4, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_dvs8x4, 0, false, "dvs8x4"},
    .Mod8x4  = {.Mod8x4, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_mod8x4, 0, false, "mod8x4"},
    .Mds8x4  = {.Mds8x4, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_mds8x4, 0, false, "mds8x4"},
    .Dvm8x4  = {
        .Dvm8x4,
        3,
        {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone},
        {.B32, .B32, .B32, .B0},
        inst_dvm8x4,
        0,
        false,
        "dvm8x4",
    },
    .Dms8x4  = {
        .Dms8x4,
        3,
        {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone},
        {.B32, .B32, .B32, .B0},
        inst_dms8x4,
        0,
        false,
        "dms8x4",
    },
    .Rem8x4  = {.Rem8x4, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_rem8x4, 0, false, "rem8x4"},
    .Rms8x4  = {.Rms8x4, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_rms8x4, 0, false, "rms8x4"},
    .Dvr8x4  = {
        .Dvr8x4,
        3,
        {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone},
        {.B32, .B32, .B32, .B0},
        inst_dvr8x4,
        0,
        false,
        "dvr8x4",
    },
    .Drs8x4  = {
        .Drs8x4,
        3,
        {AddrModeSetWriteable, AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone},
        {.B32, .B32, .B32, .B0},
        inst_drs8x4,
        0,
        false,
        "drs8x4",
    },
    .Bst8x4  = {.Bst8x4, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_bst8x4, 0, false, "bst8x4"},
    .Brs8x4  = {.Brs8x4, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_brs8x4, 0, false, "brs8x4"},
    .Shl8x4  = {.Shl8x4, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_shl8x4, 0, false, "shl8x4"},
    .Asr8x4  = {.Asr8x4, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_asr8x4, 0, false, "asr8x4"},
    .Rtl8x4  = {.Rtl8x4, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_rtl8x4, 0, false, "rtl8x4"},
    .Rtr8x4  = {.Rtr8x4, 2, {AddrModeSetWriteable, AddrModeSetAll, AddrModeSetNone, AddrModeSetNone}, {.B32, .B32, .B0, .B0}, inst_rtr8x4, 0, false, "rtr8x4"},
    // TODO: Add 32-bit floating point instructions.
}
